### ISSUE TITLE
Missing date field from data

### ISSUE THREAD

**Issue by eobrien2002** [sinking8/usc-x-24-us-election#1]
Hi! I am looking to use the data for a school project; however, I noticed that all of the date fields are missing. Could you either add these or add descriptions of which part numbers for which dates?

Thank you!!!!

**Comment by sinking8** [comment]
Hi eobrien, kindly make use of these below fields incase the date field is missing
1. epoch : UNIX timestamp
2. epoch_dt :  datetime object extracted from epoch field

**Comment by eobrien2002** [comment]
Thank you!

**Comment by eobrien2002** [comment]
Hi! Also, all the location fields are empty @sinking8

**Comment by sinking8** [comment]
Hi @eobrien2002 , the location field depends on X.com user's privacy settings. You can find most of them empty since that access was restricted.
